### ISSUE TITLE
Better deal with invalid URLs

### ISSUE THREAD

**Issue by dalepotter** [IATI/AidInfoLabs-CSV-Downloader#1]
The request:

`http://tools.aidinfolabs.org/csv/direct_from_registry/?xml=http://www.google.com`

Returns a CSV with HTML data.  URLs with no IATI data should direct to an error page.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the AidInfoLabs CSV Downloader is to be shut down.

This issue does not cause intended functionality to work incorrectly (or not at all). As such, it will not be fixed in the interim until shutdown.
